services:

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
    environment:
      HOST: "0.0.0.0"
      GROQ_API_TOKEN: ""
      INTERESTS: "cs.IT,cs.CV,cs.LG,cs.NE"
      REDIS_SERVER: "db"
      REDIS_PORT: 6379
      TZ: "Asia/Tokyo"
    depends_on:
      - db
    networks:
      - arxiv-dayli-net

  discord_webhook:
    build: ./discord_webhook
    environment:
      BACKEND_URL: "http://backend:8081"
      DISCORD_WEBHOOK_URL: ""
      DAILY_SEND_TIME: "09:00"
      TZ: "Asia/Tokyo"
      # TZ: "Asia/Taipei"
    networks:
      - arxiv-dayli-net

  db:
    restart: always
    image: redis:latest
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/data
    networks:
      - arxiv-dayli-net

networks:
  arxiv-dayli-net:
    driver: bridge